### ISSUE TITLE
Violation of API terms

### ISSUE THREAD

**Issue by frozenpandaman** [JoneWang/sp2battlebot#3]
Hi,

Your project uses my API:
https://github.com/JoneWang/sp2battlebot/blob/27d92356c993c89dca3f11b3d68b0615c6bd22c6/sp2bot/splatoon2.py#L420

Per the [s2s API docs](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs):

> If you wish use this API in your app or service, you must: 1) contact me to let me know, 2) use a unique and properly-formatted user agent string with version number for all requests, 3) transparently communicate to users that this involves making a request to a non-Nintendo server, and 4) provide an alternative method or workaround in your app, e.g. allow for and provide/link to adequate instruction on how to use mitmproxy to obtain and manually enter the cookie instead.

Correct me if I'm mistaken in any way, but I was not made aware of this project, and you did not contact me to let me know. In addition, your readme does not communicate the privacy disclosure to users. I'm not sure if your project adheres to #4 but it seems like not, or this isn't advertised/mentioned anywhere.

You are also **not providing a unique user agent to users – you are falsely masquerading requests to my server under the name of my app**:

https://github.com/JoneWang/sp2battlebot/blob/27d92356c993c89dca3f11b3d68b0615c6bd22c6/sp2bot/splatoon2.py#L418

Your project is not splatnet2statink. You are using [my code](https://github.com/frozenpandaman/splatnet2statink/blob/master/iksm.py) without changing the name of the user agent sent in requests, as required.

In that file, _you have taken a significant portion of code from my repository/project without putting it under the same license or crediting me anywhere_.

Please fix all of these things immediately. Thank you.

**Comment by JoneWang** [comment]
I am very sorry!
I will be fixing these things in the next few days.

**Comment by frozenpandaman** [comment]
Thank you, I very much appreciate it! (Especially the credit/license & user agent bits. Really helps to be able to have proper logs. 😊) Thanks again for your reassurance and the speedy reply.

**Comment by JoneWang** [comment]
> Thank you, I very much appreciate it! (Especially the credit/license & user agent bits. Really helps to be able to have proper logs. 😊) Thanks again for your reassurance and the speedy reply.

All your code has been removed from the code and bot server. I will re-write it.
If I use your API again, will let you know before submitting.
Again, my apologies.

**Comment by frozenpandaman** [comment]
@JoneWang Sounds good! Feel free to use the code if you'd still like (it's just a basic Python implementation of the API calls, after all) – it's licensed for that, and I encourage it, just please be sure to provide credit & license it properly (as the GPL licenses maintain derivative works should be distributed under the same/equivalent terms, since I want to promote this in other projects too). :)
